# jdbc配置
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/gmall?characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/gmall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
# Mapper配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

#web服务端口
server:
  port: 8080

#日志级别
logging:
  level: info
