# jdbc配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  dubbo:
    application:  redisson-web         #dubbo的配置
    protocol:
      name: dubbo                       #dubbo中的服务名称
    registry:
      address: 192.168.37.132:2181      #zookeeper注册中心的地址
      protocol: zookeeper               #zookeeper的通讯协议的名称
    base-package: com.gavin.gmall       #dubbo的服务的扫描路径
  redis:
    host: 127.0.0.1                # redis链接地址
    port: 6379                          # 端口号
    database: 0                         # 数据库

# Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml

#service服务端口
server:
  port: 8080

#日志级别
logging:
  level:
    root: info



